version: 1

accounts:
    - name: alice
      coins:
          - 100000000b52USD
      mnemonic: "mammal aim member plastic cage worth planet earth custom youth goose hawk"
    - name: bob
      coins:
          - 100000000b52USD
      mnemonic: "predict stamp narrow pencil trigger fiction legal devote omit hungry basket jaguar"

validators:
    - name: alice
      bonded: 100000000b52USD

faucet:
    name: bob
    coins:
        - 10000000b52USD
    coins_max:
        - 1000000b52USD

client:
    openapi:
        path: docs/static/openapi.yml
    typescript:
        path: ts-client

host:
    rpc: ":26657"
    p2p: ":26656"
    prof: ":6060"
    grpc: ":9090"
    grpc-web: ":9091"
    api: ":1317"
    frontend: ":5173"
    dev-ui: false

build:
    binary: "pokerchaind"
    main: "cmd/pokerchaind"
    proto:
        path: "proto"
        third_party_paths:
            - "proto_vendor"
