# Production overrides for docker-compose
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up

services:
    # Production PVM with built application
    pvm:
        build:
            target: production
        environment:
            NODE_ENV: production
        volumes: [] # Remove development volume mounts

    # Production Frontend with Nginx
    frontend:
        build:
            target: production
        environment:
            NODE_ENV: production
        ports:
            - "80:80" # Production port
            - "443:443" # HTTPS port
        volumes: [] # Remove development volume mounts

    # Production MongoDB with authentication
    mongo:
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secure_password_change_me}
        ports: [] # Don't expose externally in production

    # Production Redis with password
    redis:
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD:-secure_password_change_me}
        ports: [] # Don't expose externally in production
