# Development overrides for docker-compose
# This is the default behavior, but explicit for clarity
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up

services:
    # Development PVM with hot reload
    pvm:
        build:
            target: development
        environment:
            NODE_ENV: development
        volumes:
            - ./pvm/ts:/app:cached
            - /app/node_modules
            - /app/dist
        command: ["yarn", "dev"]

    # Development Frontend with hot reload
    frontend:
        build:
            target: development
        environment:
            NODE_ENV: development
        volumes:
            - ./ui:/app:cached
            - /app/node_modules
        command: ["yarn", "dev", "--host", "0.0.0.0"]

    # Development databases with external access
    mongo:
        ports:
            - "27017:27017"

    redis:
        ports:
            - "6379:6379"
