// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title IVerifier
 * @dev Interface for Groth16 verifier contract generated by circom
 */
interface IVerifier {
    /**
     * @dev Verify a Groth16 proof
     * @param _pA Point A of the proof
     * @param _pB Point B of the proof  
     * @param _pC Point C of the proof
     * @param publicSignals Public signals for the proof
     * @return True if proof is valid, false otherwise
     */
    function verifyProof(
        uint[2] memory _pA,
        uint[2][2] memory _pB,
        uint[2] memory _pC,
        uint[1] memory publicSignals
    ) external view returns (bool);
}