name: poker-vm

services:
  mongo:
    image: mongo:8.0.9-noble
    container_name: pvm-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: pvm
      # No auth for now
      MONGO_INITDB_ROOT_USERNAME: node1
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd123
    ports:
      - 27017:27017

  cache:
    image: redis:8.0-alpine
    container_name: pvm-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #--requirepass Test1234!
    # volumes: 
    #   - cache:/data

  pvm:
    profiles: [pvm]
    container_name: pvm
    image: pokervm-pvm
    pull_policy: build
    build:
      context: ../pvm/ts
    depends_on:
      - mongo
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway" # Needed on linux to allow us to use "host.docker.internal" in the container to connect to the host's "localhost"
    environment:
      DB_URL: "mongodb://host.docker.internal:27017/pvm" # Override the env_file value as we need to use host.docker.internal
    env_file:
      - ../pvm/ts/.env


  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - pvm
