services:
  pvm_mongo:
    container_name: local_pvm_mongodb
    image: mongo:8.0.9-noble
    restart: always
    environment:
      MONGO_INITDB_DATABASE: pvm
      # No auth for now
      MONGO_INITDB_ROOT_USERNAME: node1
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd123
    ports:
      - 27017:27017  # Different port from main node
    volumes:
      - pvm_data:/data/db

volumes:
  pvm_data: 