services:
  local_pvm_mongo:
    container_name: local_pvm_mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: local_pvm
    ports:
      - 27019:27017  # Different port from main node
    volumes:
      - local_pvm_data:/data/db

volumes:
  local_pvm_data: 